mkdir test_folder
cd test_folder
time loop 5 $i touch file$i; echo "Test $i" > file$i
exit
time clear
time mkdir "Test_Dir"
    ls
t=0
$t
reset
#exit
time ls
time cd "Test_Dir"
time touch "Test_File"
time mkdir "Test_Dir1"
time rm "Test_File"
time rm "Test_Dir1"
time ls
cd ../
time rm "Test_Dir"
time ls
time help
time echo Test
time cd ../shell
time ls
time pwd
time touch "Test_File"
time rm "Test_File"
time time
t=0
#exit